title: Ayman Boufarhi
logo: /assets/img/pic.png
description: "For my studies : I am currently pursuing a Master's degree in Artificial Intelligence and Data Science. Additionally, I enthusiastically explore graphic design as a hobby."
theme: jekyll-theme-minimal
