title: Ayman Boufarhi
logo: /assets/img/pic.png
description: "For my studies: Currently, pursuing a Master's degree in Artificial Intelligence and Data Science. As for my background, I've got over eight years of experience. I handled the management and successful growth of the Anime Arabic News Network as a blogger and content creator. Also, I dive into graphic design with enthusiasm as a hobby."
theme: jekyll-theme-minimal
